### PR TITLE
Fix deprecation warning (Error::Description)

### PR DESCRIPTION
**Pull request by guidorice**
### Context

In Rust 1.42  Error::Description is deprecated.

These calls to .description() can be removed
because the Error trait implements Display and Debug.

https://blog.rust-lang.org/2020/03/12/Rust-1.42.html#error:description-is-deprecated

cc/ @ingalls

### CODE REVIEW

**Comment by ingalls** [comment]
Fantastic!

**Comment by guidorice** [comment]
@ingalls it looks like the ci/cd step is not completed and I do not have visibility into that.

**Comment by ingalls** [comment]
@guidorice Yeah I've been forking the PRs to get them to run. Now that you're part of the org, want to change your `.git/config` to point to this repo?

**Comment by guidorice** [comment]
@ingalls ok sounds good, will do 👍

**Pull request closed without merging**
